# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sortingapi:
    image: sortingapi
    build:
      context: .
      dockerfile: SortingAPI/Dockerfile
    ports:
      - "80:80"
